import { useTranslations } from '../i18n/utils';

function getMapRoutes(t: ReturnType<typeof useTranslations>) {
  return [
    {
      id: 'nightMarkets',
      name: t('map.routes.nightMarkets.name'),
      description: t('map.routes.nightMarkets.description'),
      color: '#f39c12',
      stops: [
        {
          id: 'shilinNightMarket',
          name: t('map.stops.shilinNightMarket.name'),
          lat: 25.088,
          lng: 121.524,
          note: t('map.stops.shilinNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'raoheNightMarket',
          name: t('map.stops.raoheNightMarket.name'),
          lat: 25.051,
          lng: 121.577,
          note: t('map.stops.raoheNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'ningxiaNightMarket',
          name: t('map.stops.ningxiaNightMarket.name'),
          lat: 25.056,
          lng: 121.515,
          note: t('map.stops.ningxiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'fengjiaNightMarket',
          name: t('map.stops.fengjiaNightMarket.name'),
          lat: 24.179,
          lng: 120.647,
          note: t('map.stops.fengjiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'huayuanNightMarket',
          name: t('map.stops.huayuanNightMarket.name'),
          lat: 23.004,
          lng: 120.206,
          note: t('map.stops.huayuanNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'liuheNightMarket',
          name: t('map.stops.liuheNightMarket.name'),
          lat: 22.632,
          lng: 120.299,
          note: t('map.stops.liuheNightMarket.note'),
          link: '/food/夜市文化',
        },
      ],
    },
    {
      id: 'nationalParks',
      name: t('map.routes.nationalParks.name'),
      description: t('map.routes.nationalParks.description'),
      color: '#27ae60',
      stops: [
        {
          id: 'yangmingshanNationalPark',
          name: t('map.stops.yangmingshanNationalPark.name'),
          lat: 25.158,
          lng: 121.549,
          note: t('map.stops.yangmingshanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'tarokoNationalPark',
          name: t('map.stops.tarokoNationalPark.name'),
          lat: 24.158,
          lng: 121.621,
          note: t('map.stops.tarokoNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'yushanNationalPark',
          name: t('map.stops.yushanNationalPark.name'),
          lat: 23.47,
          lng: 120.957,
          note: t('map.stops.yushanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'alishanScenicArea',
          name: t('map.stops.alishanScenicArea.name'),
          lat: 23.51,
          lng: 120.7,
          note: t('map.stops.alishanScenicArea.note'),
          link: '/nature/阿里山',
        },
        {
          id: 'sunMoonLakeScenicArea',
          name: t('map.stops.sunMoonLakeScenicArea.name'),
          lat: 23.863,
          lng: 120.917,
          note: t('map.stops.sunMoonLakeScenicArea.note'),
          link: '/nature/日月潭',
        },
        {
          id: 'kentingNationalPark',
          name: t('map.stops.kentingNationalPark.name'),
          lat: 21.948,
          lng: 120.803,
          note: t('map.stops.kentingNationalPark.note'),
          link: '/nature/國家公園',
        },
      ],
    },
    {
      id: 'historyTrail',
      name: t('map.routes.historyTrail.name'),
      description: t('map.routes.historyTrail.description'),
      color: '#e74c3c',
      stops: [
        {
          id: 'anpingFort',
          name: t('map.stops.anpingFort.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingFort.note'),
          link: '/history/荷蘭與西班牙殖民時期',
        },
        {
          id: 'chikanTower',
          name: t('map.stops.chikanTower.name'),
          lat: 22.998,
          lng: 120.203,
          note: t('map.stops.chikanTower.note'),
          link: '/history/鄭氏時期',
        },
        {
          id: 'lukang',
          name: t('map.stops.lukang.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukang.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'presidentialOffice',
          name: t('map.stops.presidentialOffice.name'),
          lat: 25.04,
          lng: 121.512,
          note: t('map.stops.presidentialOffice.note'),
          link: '/history/日本殖民統治',
        },
        {
          id: 'chiangKaiShekMemorialHall',
          name: t('map.stops.chiangKaiShekMemorialHall.name'),
          lat: 25.036,
          lng: 121.522,
          note: t('map.stops.chiangKaiShekMemorialHall.note'),
          link: '/history/戒嚴時期',
        },
        {
          id: 'legislativeYuan',
          name: t('map.stops.legislativeYuan.name'),
          lat: 25.044,
          lng: 121.521,
          note: t('map.stops.legislativeYuan.note'),
          link: '/society/太陽花學運',
        },
      ],
    },
    {
      id: 'oldStreets',
      name: t('map.routes.oldStreets.name'),
      description: t('map.routes.oldStreets.description'),
      color: '#9b59b6',
      stops: [
        {
          id: 'dihuaStreet',
          name: t('map.stops.dihuaStreet.name'),
          lat: 25.057,
          lng: 121.51,
          note: t('map.stops.dihuaStreet.note'),
          link: '/culture/大稻埕',
        },
        {
          id: 'jiufenOldStreet',
          name: t('map.stops.jiufenOldStreet.name'),
          lat: 25.109,
          lng: 121.845,
          note: t('map.stops.jiufenOldStreet.note'),
          link: '/culture/九份',
        },
        {
          id: 'lukangOldStreet',
          name: t('map.stops.lukangOldStreet.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukangOldStreet.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'anpingOldStreet',
          name: t('map.stops.anpingOldStreet.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingOldStreet.note'),
          link: '/history/安平',
        },
        {
          id: 'qishanOldStreet',
          name: t('map.stops.qishanOldStreet.name'),
          lat: 22.889,
          lng: 120.483,
          note: t('map.stops.qishanOldStreet.note'),
          link: '/culture/旗山',
        },
        {
          id: 'tamsuiOldStreet',
          name: t('map.stops.tamsuiOldStreet.name'),
          lat: 25.17,
          lng: 121.44,
          note: t('map.stops.tamsuiOldStreet.note'),
          link: '/culture/淡水',
        },
      ],
    },
  ];
}

type MarkerCategory =
  | 'about'
  | 'art'
  | 'culture'
  | 'economy'
  | 'food'
  | 'geography'
  | 'history'
  | 'lifestyle'
  | 'music'
  | 'nature'
  | 'people'
  | 'society'
  | 'technology';

type MarkerRegion = 'north' | 'central' | 'south' | 'east' | 'islands';

type County =
  | 'taipei'
  | 'newTaipei'
  | 'keelung'
  | 'taoyuan'
  | 'hsinchu'
  | 'miaoli'
  | 'taichung'
  | 'changhua'
  | 'nantou'
  | 'chiayi'
  | 'tainan'
  | 'kaohsiung'
  | 'pingtung'
  | 'yilan'
  | 'hualien'
  | 'taitung'
  | 'penghu'
  | 'kinmen';

interface MapMarker {
  id: string;
  type: MarkerCategory;
  title: string;
  lat: number;
  lng: number;
  category: MarkerCategory;
  region: MarkerRegion;
  link: string;
  desc: string;
  county: County;
}

function getMapMarkers(t: ReturnType<typeof useTranslations>): MapMarker[] {
  return [
    {
      id: 'founderCheYuWu',
      type: 'about',
      title: t('map.markers.founderCheYuWu.title'),
      lat: 25.033,
      lng: 121.565,
      category: 'about',
      region: 'north',
      link: '/about/%E5%89%B5%E8%BE%A6%E4%BA%BA%20%E2%80%94%20%E5%90%B3%E5%93%B2%E5%AE%87%20Che-Yu%20Wu',
      desc: t('map.markers.founderCheYuWu.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanIndigenousContemporaryArt',
      type: 'art',
      title: t('map.markers.taiwanIndigenousContemporaryArt.title'),
      lat: 25.036877,
      lng: 121.56357,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E5%8E%9F%E4%BD%8F%E6%B0%91%E7%95%B6%E4%BB%A3%E8%97%9D%E8%A1%93',
      desc: t('map.markers.taiwanIndigenousContemporaryArt.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanExperimentalNewMediaArt',
      type: 'art',
      title: t('map.markers.taiwanExperimentalNewMediaArt.title'),
      lat: 25.034797,
      lng: 121.56905,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E5%AF%A6%E9%A9%97%E8%88%87%E6%96%B0%E5%AA%92%E9%AB%94%E8%97%9D%E8%A1%93',
      desc: t('map.markers.taiwanExperimentalNewMediaArt.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanArchitecture',
      type: 'art',
      title: t('map.markers.taiwanArchitecture.title'),
      lat: 24.148,
      lng: 120.674,
      category: 'art',
      region: 'central',
      link: '/art/%E5%8F%B0%E7%81%A3%E5%BB%BA%E7%AF%89',
      desc: t('map.markers.taiwanArchitecture.desc'),
      county: 'taichung',
    },
    {
      id: 'taiwanNewMediaArt',
      type: 'art',
      title: t('map.markers.taiwanNewMediaArt.title'),
      lat: 25.039525,
      lng: 121.568751,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E6%96%B0%E5%AA%92%E9%AB%94%E8%97%9D%E8%A1%93',
      desc: t('map.markers.taiwanNewMediaArt.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanWatercolorCenturyEvolution',
      type: 'art',
      title: t('map.markers.taiwanWatercolorCenturyEvolution.title'),
      lat: 24.804,
      lng: 120.969,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E6%B0%B4%E5%BD%A9%E7%95%AB%E7%9A%84%E7%99%BE%E5%B9%B4%E6%B5%81%E8%AE%8A',
      desc: t('map.markers.taiwanWatercolorCenturyEvolution.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanModernPoetry',
      type: 'art',
      title: t('map.markers.taiwanModernPoetry.title'),
      lat: 24.081,
      lng: 120.539,
      category: 'art',
      region: 'central',
      link: '/art/%E5%8F%B0%E7%81%A3%E7%8F%BE%E4%BB%A3%E8%A9%A9',
      desc: t('map.markers.taiwanModernPoetry.desc'),
      county: 'changhua',
    },
    {
      id: 'taiwanContemporarySculpture',
      type: 'art',
      title: t('map.markers.taiwanContemporarySculpture.title'),
      lat: 25.036217,
      lng: 121.563481,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E7%95%B6%E4%BB%A3%E9%9B%95%E5%A1%91%E7%99%BC%E5%B1%95',
      desc: t('map.markers.taiwanContemporarySculpture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanCuratorsArtCulture',
      type: 'art',
      title: t('map.markers.taiwanCuratorsArtCulture.title'),
      lat: 25.038853,
      lng: 121.562315,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E7%AD%96%E5%B1%95%E4%BA%BA%E8%88%87%E8%97%9D%E8%A1%93%E6%96%87%E5%8C%96%E5%BB%BA%E6%A7%8B',
      desc: t('map.markers.taiwanCuratorsArtCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'newMediaArt',
      type: 'art',
      title: t('map.markers.newMediaArt.title'),
      lat: 25.037479,
      lng: 121.567623,
      category: 'art',
      region: 'north',
      link: '/art/%E6%96%B0%E5%AA%92%E9%AB%94%E8%97%9D%E8%A1%93',
      desc: t('map.markers.newMediaArt.desc'),
      county: 'taipei',
    },
    {
      id: 'contemporaryTaiwanLiterature',
      type: 'art',
      title: t('map.markers.contemporaryTaiwanLiterature.title'),
      lat: 25.029037,
      lng: 121.558064,
      category: 'art',
      region: 'north',
      link: '/art/%E7%95%B6%E4%BB%A3%E5%8F%B0%E7%81%A3%E6%96%87%E5%AD%B8',
      desc: t('map.markers.contemporaryTaiwanLiterature.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanContemporaryArt',
      type: 'art',
      title: t('map.markers.taiwanContemporaryArt.title'),
      lat: 25.040538,
      lng: 121.558141,
      category: 'art',
      region: 'north',
      link: '/art/%E5%8F%B0%E7%81%A3%E7%95%B6%E4%BB%A3%E8%97%9D%E8%A1%93',
      desc: t('map.markers.taiwanContemporaryArt.desc'),
      county: 'taipei',
    },
    {
      id: 'kinmenGuesthouseMuseum',
      type: 'art',
      title: t('map.markers.kinmenGuesthouseMuseum.title'),
      lat: 22.627,
      lng: 120.301,
      category: 'art',
      region: 'south',
      link: '/art/當代藝術',
      desc: t('map.markers.kinmenGuesthouseMuseum.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'renjianMagazine',
      type: 'culture',
      title: t('map.markers.renjianMagazine.title'),
      lat: 24.994,
      lng: 121.301,
      category: 'culture',
      region: 'north',
      link: '/culture/%E4%BA%BA%E9%96%93%E9%9B%9C%E8%AA%8C',
      desc: t('map.markers.renjianMagazine.desc'),
      county: 'taoyuan',
    },
    {
      id: 'taiwanIndigenousCulture',
      type: 'culture',
      title: t('map.markers.taiwanIndigenousCulture.title'),
      lat: 24.158,
      lng: 121.621,
      category: 'culture',
      region: 'east',
      link: '/culture/原住民族文化',
      desc: t('map.markers.taiwanIndigenousCulture.desc'),
      county: 'hualien',
    },
    {
      id: 'taiwan16IndigenousTribes',
      type: 'culture',
      title: t('map.markers.taiwan16IndigenousTribes.title'),
      lat: 22.682,
      lng: 120.484,
      category: 'culture',
      region: 'south',
      link: '/culture/原住民族文化',
      desc: t('map.markers.taiwan16IndigenousTribes.desc'),
      county: 'pingtung',
    },
    {
      id: 'taiwanNightMarketCulture',
      type: 'culture',
      title: t('map.markers.taiwanNightMarketCulture.title'),
      lat: 25.088,
      lng: 121.524,
      category: 'culture',
      region: 'north',
      link: '/culture/%E5%8F%B0%E7%81%A3%E5%A4%9C%E5%B8%82%E6%96%87%E5%8C%96%E8%88%87%E5%B0%8F%E5%90%83%E9%A2%A8%E6%83%85',
      desc: t('map.markers.taiwanNightMarketCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanSensibilityKoreanPerspective',
      type: 'culture',
      title: t('map.markers.taiwanSensibilityKoreanPerspective.title'),
      lat: 25.038863,
      lng: 121.558392,
      category: 'culture',
      region: 'north',
      link: '/culture/%E5%8F%B0%E7%81%A3%E6%84%9F%E6%80%A7%EF%BC%9A%E9%9F%93%E5%9C%8B%E4%BA%BA%E7%9C%BC%E4%B8%AD%E7%9A%84%E5%8F%B0%E5%BC%8F%E7%BE%8E%E5%AD%B8',
      desc: t('map.markers.taiwanSensibilityKoreanPerspective.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanCulturalCreativeParks',
      type: 'culture',
      title: t('map.markers.taiwanCulturalCreativeParks.title'),
      lat: 22.619886,
      lng: 120.274654,
      category: 'culture',
      region: 'south',
      link: '/culture/%E5%8F%B0%E7%81%A3%E6%96%87%E5%8C%96%E5%89%B5%E6%84%8F%E5%9C%92%E5%8D%80%E7%99%BC%E5%B1%95',
      desc: t('map.markers.taiwanCulturalCreativeParks.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanOldStreetCulture',
      type: 'culture',
      title: t('map.markers.taiwanOldStreetCulture.title'),
      lat: 25.109,
      lng: 121.845,
      category: 'culture',
      region: 'north',
      link: '/culture/%E5%8F%B0%E7%81%A3%E8%80%81%E8%A1%97%E6%96%87%E5%8C%96%E8%88%87%E5%95%86%E6%A5%AD%E8%A1%97%E5%8D%80',
      desc: t('map.markers.taiwanOldStreetCulture.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanTeaCeremonyLifeAesthetics',
      type: 'culture',
      title: t('map.markers.taiwanTeaCeremonyLifeAesthetics.title'),
      lat: 23.51,
      lng: 120.7,
      category: 'culture',
      region: 'south',
      link: '/culture/%E5%8F%B0%E7%81%A3%E8%8C%B6%E9%81%93%E8%88%87%E7%94%9F%E6%B4%BB%E7%BE%8E%E5%AD%B8',
      desc: t('map.markers.taiwanTeaCeremonyLifeAesthetics.desc'),
      county: 'chiayi',
    },
    {
      id: 'taiwanStreetArtGraffiti',
      type: 'culture',
      title: t('map.markers.taiwanStreetArtGraffiti.title'),
      lat: 25.035333,
      lng: 121.565941,
      category: 'culture',
      region: 'north',
      link: '/culture/%E5%8F%B0%E7%81%A3%E8%A1%97%E9%A0%AD%E8%97%9D%E8%A1%93%E8%88%87%E5%A1%97%E9%B4%89%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanStreetArtGraffiti.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanIncenseMakingCulture',
      type: 'culture',
      title: t('map.markers.taiwanIncenseMakingCulture.title'),
      lat: 24.055,
      lng: 120.437,
      category: 'culture',
      region: 'central',
      link: '/culture/%E5%8F%B0%E7%81%A3%E8%A3%BD%E9%A6%99%E6%96%87%E5%8C%96%E8%88%87%E9%A6%99%E8%85%B3%E5%8E%9F%E9%84%89',
      desc: t('map.markers.taiwanIncenseMakingCulture.desc'),
      county: 'changhua',
    },
    {
      id: 'taiwanHomophoneTaboos',
      type: 'culture',
      title: t('map.markers.taiwanHomophoneTaboos.title'),
      lat: 24.994962,
      lng: 121.298415,
      category: 'culture',
      region: 'north',
      link: '/culture/%E5%8F%B0%E7%81%A3%E8%AB%A7%E9%9F%B3%E7%A6%81%E5%BF%8C%E6%96%87%E5%8C%96%EF%BC%9A%E7%82%BA%E4%BB%80%E9%BA%BC%E3%80%8C%E5%9B%9B%E3%80%8D%E8%AE%93%E6%95%B4%E5%80%8B%E7%A4%BE%E6%9C%83%E8%B7%B3%E9%81%8E%E6%A8%93%E5%B1%A4%EF%BC%9F',
      desc: t('map.markers.taiwanHomophoneTaboos.desc'),
      county: 'taoyuan',
    },
    {
      id: 'hakkaCultureLanguage',
      type: 'culture',
      title: t('map.markers.hakkaCultureLanguage.title'),
      lat: 24.79904,
      lng: 120.968717,
      category: 'culture',
      region: 'north',
      link: '/culture/族群（閩南客家原住民外省新住民）',
      desc: t('map.markers.hakkaCultureLanguage.desc'),
      county: 'hsinchu',
    },
    {
      id: 'ethnicGroupsTaiwan',
      type: 'culture',
      title: t('map.markers.ethnicGroupsTaiwan.title'),
      lat: 24.987632,
      lng: 121.30751,
      category: 'culture',
      region: 'north',
      link: '/culture/原住民族文化',
      desc: t('map.markers.ethnicGroupsTaiwan.desc'),
      county: 'taoyuan',
    },
    {
      id: 'chinaSteel',
      type: 'economy',
      title: t('map.markers.chinaSteel.title'),
      lat: 22.621597,
      lng: 120.297853,
      category: 'economy',
      region: 'south',
      link: '/economy/%E4%B8%AD%E9%8B%BC%EF%BC%9A%E9%90%B5%E9%A0%AD%E9%83%A8%E9%95%B7%E8%88%87%E5%8D%81%E5%A4%A7%E5%BB%BA%E8%A8%AD%E7%9A%84%E9%8B%BC%E9%90%B5%E5%82%B3%E5%A5%87',
      desc: t('map.markers.chinaSteel.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanCement',
      type: 'economy',
      title: t('map.markers.taiwanCement.title'),
      lat: 22.996,
      lng: 120.161,
      category: 'economy',
      region: 'south',
      link: '/economy/%E5%8F%B0%E6%B3%A5%EF%BC%9A%E5%8F%B0%E7%81%A3%E7%AC%AC%E4%B8%80%E4%B8%8A%E5%B8%82%E5%85%AC%E5%8F%B8%E7%9A%84%E7%B6%A0%E8%89%B2%E8%BD%89%E5%9E%8B%E5%82%B3%E5%A5%87',
      desc: t('map.markers.taiwanCement.desc'),
      county: 'tainan',
    },
    {
      id: 'tsmc',
      type: 'economy',
      title: t('map.markers.tsmc.title'),
      lat: 24.799768,
      lng: 120.974677,
      category: 'economy',
      region: 'north',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E5%8F%B0%E7%A9%8D%E9%9B%BB',
      desc: t('map.markers.tsmc.desc'),
      county: 'hsinchu',
    },
    {
      id: 'chimeiCorporation',
      type: 'economy',
      title: t('map.markers.chimeiCorporation.title'),
      lat: 22.935,
      lng: 120.226,
      category: 'economy',
      region: 'south',
      link: '/art/當代藝術',
      desc: t('map.markers.chimeiCorporation.desc'),
      county: 'tainan',
    },
    {
      id: 'acer',
      type: 'economy',
      title: t('map.markers.acer.title'),
      lat: 24.987192,
      lng: 121.297448,
      category: 'economy',
      region: 'north',
      link: '/economy/%E5%AE%8F%E7%A2%81%E9%9B%86%E5%9C%98%20(Acer)%20-%20PC%20%E7%94%A2%E6%A5%AD%E7%9A%84%E8%AE%8A%E9%9D%A9%E5%85%88%E9%A9%85',
      desc: t('map.markers.acer.desc'),
      county: 'taoyuan',
    },
    {
      id: 'giantBicycles',
      type: 'economy',
      title: t('map.markers.giantBicycles.title'),
      lat: 25.029839,
      lng: 121.571398,
      category: 'economy',
      region: 'north',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E5%B7%A8%E5%A4%A7%E6%A9%9F%E6%A2%B0',
      desc: t('map.markers.giantBicycles.desc'),
      county: 'taipei',
    },
    {
      id: 'quantaComputer',
      type: 'economy',
      title: t('map.markers.quantaComputer.title'),
      lat: 25.036524,
      lng: 121.561221,
      category: 'economy',
      region: 'north',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E5%BB%A3%E9%81%94%E9%9B%BB%E8%85%A6',
      desc: t('map.markers.quantaComputer.desc'),
      county: 'taipei',
    },
    {
      id: 'aseGroup',
      type: 'economy',
      title: t('map.markers.aseGroup.title'),
      lat: 22.632532,
      lng: 120.30745,
      category: 'economy',
      region: 'south',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E6%97%A5%E6%9C%88%E5%85%89%E5%8D%8A%E5%B0%8E%E9%AB%94',
      desc: t('map.markers.aseGroup.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'esunFinancialHolding',
      type: 'economy',
      title: t('map.markers.esunFinancialHolding.title'),
      lat: 23.47,
      lng: 120.957,
      category: 'economy',
      region: 'central',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E7%8E%89%E5%B1%B1%E9%87%91%E6%8E%A7',
      desc: t('map.markers.esunFinancialHolding.desc'),
      county: 'nantou',
    },
    {
      id: 'changChunPetrochemical',
      type: 'economy',
      title: t('map.markers.changChunPetrochemical.title'),
      lat: 22.999,
      lng: 120.227,
      category: 'economy',
      region: 'south',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E9%95%B7%E6%98%A5%E7%9F%B3%E5%8C%96',
      desc: t('map.markers.changChunPetrochemical.desc'),
      county: 'tainan',
    },
    {
      id: 'formosaPlasticsGroup',
      type: 'economy',
      title: t('map.markers.formosaPlasticsGroup.title'),
      lat: 25.040109,
      lng: 121.563734,
      category: 'economy',
      region: 'north',
      link: '/economy/%E5%8F%B0%E7%81%A3%E4%BC%81%E6%A5%AD%EF%BC%9A%E9%95%B7%E6%A6%AE%E6%B5%B7%E9%81%8B',
      desc: t('map.markers.formosaPlasticsGroup.desc'),
      county: 'taipei',
    },
    {
      id: 'taipeiFubon',
      type: 'economy',
      title: t('map.markers.taipeiFubon.title'),
      lat: 24.179,
      lng: 120.647,
      category: 'economy',
      region: 'central',
      link: '/economy/%E5%A4%9C%E5%B8%82%E7%B6%93%E6%BF%9F%E5%AD%B8%EF%BC%9A%E4%B8%80%E5%A0%B4%E6%B2%92%E6%9C%89%E5%93%81%E7%89%8C%E7%9A%84%E5%95%86%E6%A5%AD%E5%A5%87%E8%B9%9F',
      desc: t('map.markers.taipeiFubon.desc'),
      county: 'taichung',
    },
    {
      id: 'taiwan7Eleven',
      type: 'food',
      title: t('map.markers.taiwan7Eleven.title'),
      lat: 23.509893,
      lng: 120.700177,
      category: 'food',
      region: 'south',
      link: '/food/%E5%8F%B0%E7%81%A3%E5%92%96%E5%95%A1%E7%94%A2%E6%A5%AD',
      desc: t('map.markers.taiwan7Eleven.desc'),
      county: 'chiayi',
    },
    {
      id: 'taiwanHighSpeedRail',
      type: 'food',
      title: t('map.markers.taiwanHighSpeedRail.title'),
      lat: 24.806384,
      lng: 120.969141,
      category: 'food',
      region: 'north',
      link: '/food/%E5%8F%B0%E7%81%A3%E5%9C%B0%E6%96%B9%E5%B0%8F%E5%90%83%E5%9C%B0%E5%9C%96',
      desc: t('map.markers.taiwanHighSpeedRail.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanSemiconductorIndustry',
      type: 'food',
      title: t('map.markers.taiwanSemiconductorIndustry.title'),
      lat: 23.48,
      lng: 120.449,
      category: 'food',
      region: 'south',
      link: '/food/%E5%8F%B0%E7%81%A3%E6%89%8B%E8%B7%AF%E8%8F%9C%EF%BC%9A%E6%AD%A3%E5%9C%A8%E6%B6%88%E5%A4%B1%E7%9A%84%E5%91%B3%E8%A6%BA%E8%A8%98%E6%86%B6',
      desc: t('map.markers.taiwanSemiconductorIndustry.desc'),
      county: 'chiayi',
    },
    {
      id: 'taiwanBankingSystem',
      type: 'food',
      title: t('map.markers.taiwanBankingSystem.title'),
      lat: 25.032194,
      lng: 121.564109,
      category: 'food',
      region: 'north',
      link: '/food/%E5%8F%B0%E7%81%A3%E6%96%B0%E4%BD%8F%E6%B0%91%E7%BE%8E%E9%A3%9F%E8%9E%8D%E5%90%88',
      desc: t('map.markers.taiwanBankingSystem.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanSmes',
      type: 'food',
      title: t('map.markers.taiwanSmes.title'),
      lat: 22.625168,
      lng: 120.299583,
      category: 'food',
      region: 'south',
      link: '/food/%E5%8F%B0%E7%81%A3%E6%B0%B4%E6%9E%9C%E7%8E%8B%E5%9C%8B',
      desc: t('map.markers.taiwanSmes.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'youbikePublicBikeSystem',
      type: 'food',
      title: t('map.markers.youbikePublicBikeSystem.title'),
      lat: 25.128,
      lng: 121.739,
      category: 'food',
      region: 'north',
      link: '/food/%E5%8F%B0%E7%81%A3%E6%B5%B7%E9%AE%AE%E6%96%87%E5%8C%96',
      desc: t('map.markers.youbikePublicBikeSystem.desc'),
      county: 'keelung',
    },
    {
      id: 'taiwanFoodBeverageIndustry',
      type: 'food',
      title: t('map.markers.taiwanFoodBeverageIndustry.title'),
      lat: 25.026687,
      lng: 121.565378,
      category: 'food',
      region: 'north',
      link: '/food/%E5%8F%B0%E7%81%A3%E7%B1%B3%E5%85%B6%E6%9E%97%E8%88%87%E7%B2%BE%E7%B7%BB%E9%A4%90%E9%A3%B2',
      desc: t('map.markers.taiwanFoodBeverageIndustry.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanAgriculturalReform',
      type: 'food',
      title: t('map.markers.taiwanAgriculturalReform.title'),
      lat: 25.092651,
      lng: 121.529039,
      category: 'food',
      region: 'north',
      link: '/food/夜市文化',
      desc: t('map.markers.taiwanAgriculturalReform.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanTeaIndustry',
      type: 'food',
      title: t('map.markers.taiwanTeaIndustry.title'),
      lat: 24.800737,
      lng: 120.967914,
      category: 'food',
      region: 'north',
      link: '/food/%E5%AE%A2%E5%AE%B6%E9%A3%B2%E9%A3%9F%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanTeaIndustry.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanFishingIndustry',
      type: 'food',
      title: t('map.markers.taiwanFishingIndustry.title'),
      lat: 25.027848,
      lng: 121.56649,
      category: 'food',
      region: 'north',
      link: '/food/%E7%89%9B%E8%82%89%E9%BA%B5',
      desc: t('map.markers.taiwanFishingIndustry.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanFruitIndustry',
      type: 'food',
      title: t('map.markers.taiwanFruitIndustry.title'),
      lat: 25.035405,
      lng: 121.570648,
      category: 'food',
      region: 'north',
      link: '/food/台灣茶文化',
      desc: t('map.markers.taiwanFruitIndustry.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanRiceVarieties',
      type: 'geography',
      title: t('map.markers.taiwanRiceVarieties.title'),
      lat: 25.027325,
      lng: 121.57157,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%9C%A8%E6%90%96%E6%99%83%E7%9A%84%E5%B3%B6%E5%B6%BC%E4%B8%8A%EF%BC%8C%E4%BB%96%E5%80%91%E8%93%8B%E4%BA%86%E4%B8%80%E5%BA%A7%E8%83%BD%E9%A3%9B%E7%9A%84%E5%A1%94',
      desc: t('map.markers.taiwanRiceVarieties.desc'),
      county: 'taipei',
    },
    {
      id: 'nightMarketCulture',
      type: 'geography',
      title: t('map.markers.nightMarketCulture.title'),
      lat: 23.465957,
      lng: 120.964078,
      category: 'geography',
      region: 'central',
      link: '/geography/%E5%8F%B0%E7%81%A3%E4%BA%94%E5%A4%A7%E5%9C%B0%E5%BD%A2%E8%88%87%E5%9C%B0%E7%90%86%E7%B5%90%E6%A7%8B%EF%BC%9A%E5%BE%9E%E5%B1%B1%E8%84%88%E5%88%B0%E5%B9%B3%E5%8E%9F%E7%9A%84%E5%B3%B6%E5%B6%BC%E9%A2%A8%E8%B2%8C',
      desc: t('map.markers.nightMarketCulture.desc'),
      county: 'nantou',
    },
    {
      id: 'bubbleTeaGlobalPhenomenon',
      type: 'geography',
      title: t('map.markers.bubbleTeaGlobalPhenomenon.title'),
      lat: 25.035791,
      lng: 121.56683,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E4%BA%A4%E9%80%9A%E9%81%8B%E8%BC%B8%E7%B6%B2%E7%B5%A1',
      desc: t('map.markers.bubbleTeaGlobalPhenomenon.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanBeefNoodle',
      type: 'geography',
      title: t('map.markers.taiwanBeefNoodle.title'),
      lat: 23.50588,
      lng: 120.699299,
      category: 'geography',
      region: 'south',
      link: '/geography/%E5%8F%B0%E7%81%A3%E5%9C%8B%E5%AE%B6%E9%A2%A8%E6%99%AF%E5%8D%80%E7%B3%BB%E7%B5%B1',
      desc: t('map.markers.taiwanBeefNoodle.desc'),
      county: 'chiayi',
    },
    {
      id: 'taiwanHotPotCulture',
      type: 'geography',
      title: t('map.markers.taiwanHotPotCulture.title'),
      lat: 23.504116,
      lng: 120.701886,
      category: 'geography',
      region: 'south',
      link: '/geography/%E5%8F%B0%E7%81%A3%E5%B3%B6%E5%B6%BC%E5%9C%B0%E7%90%86%E7%89%B9%E8%89%B2%E8%88%87%E5%BD%A2%E6%88%90',
      desc: t('map.markers.taiwanHotPotCulture.desc'),
      county: 'chiayi',
    },
    {
      id: 'taiwanFineDining',
      type: 'geography',
      title: t('map.markers.taiwanFineDining.title'),
      lat: 25.033121,
      lng: 121.565936,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%9D%BF%E5%A1%8A%E9%81%8B%E5%8B%95%E8%88%87%E5%9C%B0%E9%9C%87%E6%B4%BB%E5%8B%95',
      desc: t('map.markers.taiwanFineDining.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanStreetFood',
      type: 'geography',
      title: t('map.markers.taiwanStreetFood.title'),
      lat: 25.03885,
      lng: 121.557146,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%B0%B4%E5%BA%AB%E8%88%87%E6%B0%B4%E8%B3%87%E6%BA%90%E7%AE%A1%E7%90%86',
      desc: t('map.markers.taiwanStreetFood.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanVegetarianCulture',
      type: 'geography',
      title: t('map.markers.taiwanVegetarianCulture.title'),
      lat: 25.17,
      lng: 121.44,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%B2%B3%E5%B7%9D%E7%B3%BB%E7%B5%B1%E8%88%87%E6%B0%B4%E6%96%87%E7%89%B9%E8%89%B2%EF%BC%9A%E7%9F%AD%E6%80%A5%E6%B5%81%E8%88%87%E5%AD%A3%E7%AF%80%E8%AE%8A%E9%81%B7%E7%9A%84%E6%B0%B4%E6%96%87%E5%9C%B0%E7%90%86',
      desc: t('map.markers.taiwanVegetarianCulture.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanCoffeeCulture',
      type: 'geography',
      title: t('map.markers.taiwanCoffeeCulture.title'),
      lat: 25.206,
      lng: 121.691,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%B5%B7%E5%B2%B8%E5%9C%B0%E5%BD%A2%E8%88%87%E6%B5%B7%E6%B4%8B%E5%9C%B0%E6%99%AF',
      desc: t('map.markers.taiwanCoffeeCulture.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanSnackCulture',
      type: 'geography',
      title: t('map.markers.taiwanSnackCulture.title'),
      lat: 22.695,
      lng: 121.032,
      category: 'geography',
      region: 'east',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%BA%AB%E6%B3%89%E5%9C%B0%E6%99%AF',
      desc: t('map.markers.taiwanSnackCulture.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanSeafoodCulture',
      type: 'geography',
      title: t('map.markers.taiwanSeafoodCulture.title'),
      lat: 23.46833,
      lng: 120.95854,
      category: 'geography',
      region: 'central',
      link: '/geography/%E5%8F%B0%E7%81%A3%E7%94%9F%E6%85%8B%E5%A4%9A%E6%A8%A3%E6%80%A7%E7%86%B1%E9%BB%9E',
      desc: t('map.markers.taiwanSeafoodCulture.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanPineappleCake',
      type: 'geography',
      title: t('map.markers.taiwanPineappleCake.title'),
      lat: 24.077649,
      lng: 120.531046,
      category: 'geography',
      region: 'central',
      link: '/geography/%E5%8F%B0%E7%81%A3%E8%BE%B2%E6%A5%AD%E5%9C%B0%E6%99%AF%E8%88%87%E7%94%A2%E6%A5%AD%E5%88%86%E5%B8%83',
      desc: t('map.markers.taiwanPineappleCake.desc'),
      county: 'changhua',
    },
    {
      id: 'taiwanPorkRibSoup',
      type: 'geography',
      title: t('map.markers.taiwanPorkRibSoup.title'),
      lat: 25.025308,
      lng: 121.565368,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E9%83%BD%E5%B8%82%E7%99%BC%E5%B1%95%E8%88%87%E5%9F%8E%E9%84%89%E5%B7%AE%E8%B7%9D',
      desc: t('map.markers.taiwanPorkRibSoup.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanOysterOmelette',
      type: 'geography',
      title: t('map.markers.taiwanOysterOmelette.title'),
      lat: 23.475131,
      lng: 120.964152,
      category: 'geography',
      region: 'central',
      link: '/geography/%E5%9C%B0%E5%BD%A2%E8%88%87%E5%9C%B0%E8%B3%AA',
      desc: t('map.markers.taiwanOysterOmelette.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanBreakfastCulture',
      type: 'geography',
      title: t('map.markers.taiwanBreakfastCulture.title'),
      lat: 25.031939,
      lng: 121.561116,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%9F%8E%E5%B8%82%E7%89%B9%E8%89%B2%E8%88%87%E5%8D%80%E5%9F%9F%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanBreakfastCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanConvenienceStoreFood',
      type: 'geography',
      title: t('map.markers.taiwanConvenienceStoreFood.title'),
      lat: 23.571,
      lng: 119.579,
      category: 'geography',
      region: 'islands',
      link: '/geography/%E9%9B%A2%E5%B3%B6%E8%88%87%E6%B5%B7%E6%B4%8B%E6%96%87%E5%8C%96%EF%BC%9A%E5%BE%9E%E7%9F%B3%E6%BB%AC%E5%AF%86%E5%BA%A6%E4%B8%96%E7%95%8C%E7%AC%AC%E4%B8%80%E5%88%B0%E9%A3%9B%E9%AD%9A%E5%AD%A3%E7%94%9F%E6%85%8B%E6%B3%95%E5%BE%8B',
      desc: t('map.markers.taiwanConvenienceStoreFood.desc'),
      county: 'penghu',
    },
    {
      id: 'dutchSpanishColonialPeriod',
      type: 'history',
      title: t('map.markers.dutchSpanishColonialPeriod.title'),
      lat: 22.661,
      lng: 121.497,
      category: 'history',
      region: 'east',
      link: '/history/%E4%BA%8C%E4%BA%8C%E5%85%AB%E4%BA%8B%E4%BB%B6%E8%88%87%E7%99%BD%E8%89%B2%E6%81%90%E6%80%96%EF%BC%9A%E5%8F%B0%E7%81%A3%E5%A8%81%E6%AC%8A%E7%B5%B1%E6%B2%BB%E4%B8%8B%E7%9A%84%E5%89%B5%E5%82%B7%E8%88%87%E8%A8%98%E6%86%B6',
      desc: t('map.markers.dutchSpanishColonialPeriod.desc'),
      county: 'taitung',
    },
    {
      id: 'zhengDynastyPeriod',
      type: 'history',
      title: t('map.markers.zhengDynastyPeriod.title'),
      lat: 24.449,
      lng: 118.377,
      category: 'history',
      region: 'islands',
      link: '/history/%E5%8F%B0%E6%B5%B7%E5%8D%B1%E6%A9%9F%E8%88%87%E5%85%A9%E5%B2%B8%E9%97%9C%E4%BF%82%E7%99%BC%E5%B1%95',
      desc: t('map.markers.zhengDynastyPeriod.desc'),
      county: 'kinmen',
    },
    {
      id: 'qingDynastyTaiwanHistory',
      type: 'history',
      title: t('map.markers.qingDynastyTaiwanHistory.title'),
      lat: 22.991918,
      lng: 120.16319,
      category: 'history',
      region: 'south',
      link: '/history/%E5%8F%B0%E7%81%A3%E6%B5%B7%E6%B4%8B%E8%B2%BF%E6%98%93%E5%8F%B2',
      desc: t('map.markers.qingDynastyTaiwanHistory.desc'),
      county: 'tainan',
    },
    {
      id: 'japaneseColonialRule',
      type: 'history',
      title: t('map.markers.japaneseColonialRule.title'),
      lat: 25.025798,
      lng: 121.559275,
      category: 'history',
      region: 'north',
      link: '/history/%E5%8F%B0%E7%81%A3%E7%9C%B7%E6%9D%91%E6%AD%B7%E5%8F%B2',
      desc: t('map.markers.japaneseColonialRule.desc'),
      county: 'taipei',
    },
    {
      id: 'februaryTwentyEightIncident',
      type: 'history',
      title: t('map.markers.februaryTwentyEightIncident.title'),
      lat: 23.510488,
      lng: 120.698955,
      category: 'history',
      region: 'south',
      link: '/history/%E5%8F%B0%E7%81%A3%E9%90%B5%E9%81%93%E5%8F%B2',
      desc: t('map.markers.februaryTwentyEightIncident.desc'),
      county: 'chiayi',
    },
    {
      id: 'martialLawPeriod',
      type: 'history',
      title: t('map.markers.martialLawPeriod.title'),
      lat: 25.032225,
      lng: 121.565142,
      category: 'history',
      region: 'north',
      link: '/history/%E5%9C%8B%E6%B0%91%E6%94%BF%E5%BA%9C%E9%81%B7%E5%8F%B0%E8%88%87%E6%88%B0%E5%BE%8C%E9%87%8D%E5%BB%BA',
      desc: t('map.markers.martialLawPeriod.desc'),
      county: 'taipei',
    },
    {
      id: 'democratization',
      type: 'history',
      title: t('map.markers.democratization.title'),
      lat: 22.633777,
      lng: 120.306787,
      category: 'history',
      region: 'south',
      link: '/history/%E6%97%A5%E6%B2%BB%E6%99%82%E6%9C%9F',
      desc: t('map.markers.democratization.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanIndependenceMovement',
      type: 'history',
      title: t('map.markers.taiwanIndependenceMovement.title'),
      lat: 25.172532,
      lng: 121.44378,
      category: 'history',
      region: 'north',
      link: '/history/%E6%B8%85%E6%B2%BB%E6%99%82%E6%9C%9F',
      desc: t('map.markers.taiwanIndependenceMovement.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanChinaRelations',
      type: 'history',
      title: t('map.markers.taiwanChinaRelations.title'),
      lat: 25.175524,
      lng: 121.442089,
      category: 'history',
      region: 'north',
      link: '/history/%E8%8D%B7%E8%A5%BF%E6%98%8E%E9%84%AD%E6%99%82%E6%9C%9F',
      desc: t('map.markers.taiwanChinaRelations.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanUsRelations',
      type: 'lifestyle',
      title: t('map.markers.taiwanUsRelations.title'),
      lat: 25.038916,
      lng: 121.563341,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E4%BE%BF%E5%88%A9%E5%95%86%E5%BA%97%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanUsRelations.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanInternationalStatus',
      type: 'lifestyle',
      title: t('map.markers.taiwanInternationalStatus.title'),
      lat: 25.034413,
      lng: 121.560259,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E4%BA%A4%E9%80%9A%E7%B3%BB%E7%B5%B1',
      desc: t('map.markers.taiwanInternationalStatus.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanHistoricalFigures',
      type: 'lifestyle',
      title: t('map.markers.taiwanHistoricalFigures.title'),
      lat: 25.027898,
      lng: 121.566293,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E4%BE%BF%E5%88%A9%E5%95%86%E5%BA%97%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanHistoricalFigures.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanPoliticalFigures',
      type: 'lifestyle',
      title: t('map.markers.taiwanPoliticalFigures.title'),
      lat: 25.037251,
      lng: 121.563647,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E5%85%AC%E5%9C%92%E8%88%87%E6%97%A5%E5%B8%B8%E4%BC%91%E9%96%92',
      desc: t('map.markers.taiwanPoliticalFigures.desc'),
      county: 'taipei',
    },
    {
      id: 'kuomintangHistory',
      type: 'lifestyle',
      title: t('map.markers.kuomintangHistory.title'),
      lat: 23.508289,
      lng: 120.695627,
      category: 'lifestyle',
      region: 'south',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E5%92%96%E5%95%A1%E6%96%87%E5%8C%96',
      desc: t('map.markers.kuomintangHistory.desc'),
      county: 'chiayi',
    },
    {
      id: 'democraticProgressivePartyHistory',
      type: 'lifestyle',
      title: t('map.markers.democraticProgressivePartyHistory.title'),
      lat: 25.040839,
      lng: 121.566538,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E8%BF%BD%E5%9E%83%E5%9C%BE%E8%BB%8A%E7%9A%84%E5%B3%B6%EF%BC%9A%E5%8F%B0%E7%81%A3%E5%BE%9E%E5%9E%83%E5%9C%BE%E5%8D%B1%E6%A9%9F%E5%88%B0%E5%9B%9E%E6%94%B6%E5%A5%87%E8%B9%9F',
      desc: t('map.markers.democraticProgressivePartyHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taipeiHistory',
      type: 'lifestyle',
      title: t('map.markers.taipeiHistory.title'),
      lat: 25.03562,
      lng: 121.562542,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E6%8D%B7%E9%81%8B%E7%99%BC%E5%B1%95%E5%8F%B2%EF%BC%9A%E4%B8%80%E9%83%A8%E7%94%A8%E8%A1%80%E8%88%87%E9%8C%A2%E5%AF%AB%E6%88%90%E7%9A%84%E5%9F%8E%E5%B8%82%E9%80%B2%E5%8C%96%E8%AB%96',
      desc: t('map.markers.taipeiHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanPrehistoricCulture',
      type: 'lifestyle',
      title: t('map.markers.taiwanPrehistoricCulture.title'),
      lat: 25.030958,
      lng: 121.560701,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E6%95%99%E8%82%B2%E5%88%B6%E5%BA%A6%EF%BC%9A%E5%BE%9E%E8%81%AF%E8%80%83%E5%9C%B0%E7%8D%84%E5%88%B0%E5%A4%9A%E5%85%83%E8%BF%B7%E5%AE%AE%E7%9A%84%E5%B3%B6%E5%B6%BC%E5%AF%A6%E9%A9%97',
      desc: t('map.markers.taiwanPrehistoricCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanIndigenousHistory',
      type: 'lifestyle',
      title: t('map.markers.taiwanIndigenousHistory.title'),
      lat: 25.039881,
      lng: 121.568213,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E6%A9%9F%E8%BB%8A%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanIndigenousHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanMilitaryHistory',
      type: 'lifestyle',
      title: t('map.markers.taiwanMilitaryHistory.title'),
      lat: 25.039993,
      lng: 121.557738,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E9%A8%8E%E6%A8%93%E6%96%87%E5%8C%96%E8%88%87%E8%A1%97%E6%99%AF',
      desc: t('map.markers.taiwanMilitaryHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanWomenHistory',
      type: 'lifestyle',
      title: t('map.markers.taiwanWomenHistory.title'),
      lat: 25.040872,
      lng: 121.565048,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%A4%9C%E7%94%9F%E6%B4%BB%E8%88%87KTV%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanWomenHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanEducationHistory',
      type: 'lifestyle',
      title: t('map.markers.taiwanEducationHistory.title'),
      lat: 25.037358,
      lng: 121.568278,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%AE%97%E6%95%99%E8%88%87%E6%B0%91%E9%96%93%E4%BF%A1%E4%BB%B0%EF%BC%9A%E5%BE%9E%E6%81%90%E6%87%BC%E7%AE%A1%E7%90%86%E5%88%B0%E4%BF%A1%E4%BB%B0%E5%B8%9D%E5%9C%8B',
      desc: t('map.markers.taiwanEducationHistory.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanReligiousHistory',
      type: 'lifestyle',
      title: t('map.markers.taiwanReligiousHistory.title'),
      lat: 22.66311,
      lng: 121.494711,
      category: 'lifestyle',
      region: 'east',
      link: '/lifestyle/溫泉文化',
      desc: t('map.markers.taiwanReligiousHistory.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanMediaHistory',
      type: 'music',
      title: t('map.markers.taiwanMediaHistory.title'),
      lat: 22.67578,
      lng: 120.491069,
      category: 'music',
      region: 'south',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.taiwanMediaHistory.desc'),
      county: 'pingtung',
    },
    {
      id: 'badmintonChampions',
      type: 'music',
      title: t('map.markers.badmintonChampions.title'),
      lat: 23.863,
      lng: 120.917,
      category: 'music',
      region: 'central',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.badmintonChampions.desc'),
      county: 'nantou',
    },
    {
      id: 'baseballCulture',
      type: 'music',
      title: t('map.markers.baseballCulture.title'),
      lat: 25.035764,
      lng: 121.558898,
      category: 'music',
      region: 'north',
      link: '/music/%E5%8F%B0%E7%81%A3%E6%B0%91%E6%AD%8C%E9%81%8B%E5%8B%95',
      desc: t('map.markers.baseballCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanBasketball',
      type: 'music',
      title: t('map.markers.taiwanBasketball.title'),
      lat: 25.028825,
      lng: 121.57143,
      category: 'music',
      region: 'north',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.taiwanBasketball.desc'),
      county: 'taipei',
    },
    {
      id: 'marathonRunning',
      type: 'music',
      title: t('map.markers.marathonRunning.title'),
      lat: 25.027798,
      lng: 121.567108,
      category: 'music',
      region: 'north',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.marathonRunning.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanEsports',
      type: 'music',
      title: t('map.markers.taiwanEsports.title'),
      lat: 21.948,
      lng: 120.803,
      category: 'music',
      region: 'south',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.taiwanEsports.desc'),
      county: 'pingtung',
    },
    {
      id: 'taiwanOlympics',
      type: 'music',
      title: t('map.markers.taiwanOlympics.title'),
      lat: 22.623478,
      lng: 120.303183,
      category: 'music',
      region: 'south',
      link: '/music/流行音樂與金曲獎',
      desc: t('map.markers.taiwanOlympics.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taipeiCycle',
      type: 'nature',
      title: t('map.markers.taipeiCycle.title'),
      lat: 23.992,
      lng: 121.602,
      category: 'nature',
      region: 'east',
      link: '/nature/%E5%8F%B0%E7%81%A3%E5%8E%9F%E4%BD%8F%E6%B0%91%E7%94%9F%E6%85%8B%E6%99%BA%E6%85%A7%E8%88%87%E7%92%B0%E5%A2%83%E4%BF%9D%E8%82%B2',
      desc: t('map.markers.taipeiCycle.desc'),
      county: 'hualien',
    },
    {
      id: 'taiwanBetelNutCulture',
      type: 'nature',
      title: t('map.markers.taiwanBetelNutCulture.title'),
      lat: 23.466976,
      lng: 120.949567,
      category: 'nature',
      region: 'central',
      link: '/nature/%E5%8F%B0%E7%81%A3%E5%B1%B1%E5%B2%B3%E8%88%87%E7%99%BB%E5%B1%B1%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanBetelNutCulture.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanElections',
      type: 'nature',
      title: t('map.markers.taiwanElections.title'),
      lat: 23.469207,
      lng: 120.961177,
      category: 'nature',
      region: 'central',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%A3%AE%E6%9E%97%E7%94%9F%E6%85%8B%E7%B3%BB',
      desc: t('map.markers.taiwanElections.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanLgbtCulture',
      type: 'nature',
      title: t('map.markers.taiwanLgbtCulture.title'),
      lat: 22.621528,
      lng: 120.303635,
      category: 'nature',
      region: 'south',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%B0%A3%E5%80%99%E8%AE%8A%E9%81%B7%E8%88%87%E6%B7%A8%E9%9B%B6%E8%BD%89%E5%9E%8B',
      desc: t('map.markers.taiwanLgbtCulture.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanMotorcycleCulture',
      type: 'nature',
      title: t('map.markers.taiwanMotorcycleCulture.title'),
      lat: 22.338,
      lng: 120.373,
      category: 'nature',
      region: 'south',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%B5%B7%E6%B4%8B%E4%BF%9D%E8%82%B2%EF%BC%9A%E7%82%BA%E4%BB%80%E9%BA%BC%E8%8A%B130%E5%B9%B4%E5%BB%BA%E6%88%90%E7%9A%84%E9%AB%94%E7%B3%BB%EF%BC%8C%E6%95%91%E4%B8%8D%E4%BA%86%E4%B8%80%E5%A0%B4%E7%8F%8A%E7%91%9A%E7%99%BD%E5%8C%96%EF%BC%9F',
      desc: t('map.markers.taiwanMotorcycleCulture.desc'),
      county: 'pingtung',
    },
    {
      id: 'taipeiMrt',
      type: 'nature',
      title: t('map.markers.taipeiMrt.title'),
      lat: 22.345501,
      lng: 120.378291,
      category: 'nature',
      region: 'south',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%B5%B7%E6%B4%8B%E6%B1%A1%E6%9F%93%E6%B2%BB%E7%90%86%E8%88%87%E4%BF%9D%E8%82%B2%E6%8C%91%E6%88%B0',
      desc: t('map.markers.taipeiMrt.desc'),
      county: 'pingtung',
    },
    {
      id: 'kaohsiungMrt',
      type: 'nature',
      title: t('map.markers.kaohsiungMrt.title'),
      lat: 22.033,
      lng: 121.549,
      category: 'nature',
      region: 'east',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%B5%B7%E6%B4%8B%E7%94%9F%E6%85%8B',
      desc: t('map.markers.kaohsiungMrt.desc'),
      county: 'taitung',
    },
    {
      id: 'taichungMrt',
      type: 'nature',
      title: t('map.markers.taichungMrt.title'),
      lat: 21.955912,
      lng: 120.809936,
      category: 'nature',
      region: 'south',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%B5%B7%E6%B4%8B%E7%94%9F%E6%85%8B%E8%88%87%E7%8F%8A%E7%91%9A%E7%A4%81%E4%BF%9D%E8%82%B2',
      desc: t('map.markers.taichungMrt.desc'),
      county: 'pingtung',
    },
    {
      id: 'taiwanTrainSystem',
      type: 'nature',
      title: t('map.markers.taiwanTrainSystem.title'),
      lat: 22.665641,
      lng: 121.493931,
      category: 'nature',
      region: 'east',
      link: '/nature/%E5%8F%B0%E7%81%A3%E6%BA%AB%E6%B3%89%E8%88%87%E5%9C%B0%E7%86%B1',
      desc: t('map.markers.taiwanTrainSystem.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanBusSystem',
      type: 'nature',
      title: t('map.markers.taiwanBusSystem.title'),
      lat: 24.561,
      lng: 120.821,
      category: 'nature',
      region: 'central',
      link: '/nature/%E5%8F%B0%E7%81%A3%E7%9F%B3%E8%99%8E%E4%BF%9D%E8%82%B2',
      desc: t('map.markers.taiwanBusSystem.desc'),
      county: 'miaoli',
    },
    {
      id: 'taiwanInnovationEcosystem',
      type: 'nature',
      title: t('map.markers.taiwanInnovationEcosystem.title'),
      lat: 25.029597,
      lng: 121.568745,
      category: 'nature',
      region: 'north',
      link: '/nature/%E5%8F%B0%E7%81%A3%E7%A9%BF%E5%B1%B1%E7%94%B2',
      desc: t('map.markers.taiwanInnovationEcosystem.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanMedicalSystem',
      type: 'nature',
      title: t('map.markers.taiwanMedicalSystem.title'),
      lat: 23.474176,
      lng: 120.959436,
      category: 'nature',
      region: 'central',
      link: '/nature/%E5%8F%B0%E7%81%A3%E9%AB%98%E5%B1%B1%E7%94%9F%E6%85%8B%E7%B3%BB%E8%88%87%E5%86%B0%E6%B2%B3%E5%AD%91%E9%81%BA',
      desc: t('map.markers.taiwanMedicalSystem.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanEducationSystem',
      type: 'nature',
      title: t('map.markers.taiwanEducationSystem.title'),
      lat: 25.03383,
      lng: 121.572971,
      category: 'nature',
      region: 'north',
      link: '/nature/%E5%8F%B0%E7%81%A3%E9%BB%91%E7%86%8A',
      desc: t('map.markers.taiwanEducationSystem.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanMusicIndustry',
      type: 'nature',
      title: t('map.markers.taiwanMusicIndustry.title'),
      lat: 24.155453,
      lng: 121.621324,
      category: 'nature',
      region: 'east',
      link: '/nature/國家公園',
      desc: t('map.markers.taiwanMusicIndustry.desc'),
      county: 'hualien',
    },
    {
      id: 'mandarinPopMusic',
      type: 'nature',
      title: t('map.markers.mandarinPopMusic.title'),
      lat: 23.463851,
      lng: 120.950975,
      category: 'nature',
      region: 'central',
      link: '/nature/國家公園',
      desc: t('map.markers.mandarinPopMusic.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwaneseIndieMusic',
      type: 'nature',
      title: t('map.markers.taiwaneseIndieMusic.title'),
      lat: 23.47604,
      lng: 120.959797,
      category: 'nature',
      region: 'central',
      link: '/nature/%E7%89%B9%E6%9C%89%E7%A8%AE',
      desc: t('map.markers.taiwaneseIndieMusic.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanRapHipHop',
      type: 'nature',
      title: t('map.markers.taiwanRapHipHop.title'),
      lat: 23.46676,
      lng: 120.961061,
      category: 'nature',
      region: 'central',
      link: '/nature/%E7%94%9F%E6%85%8B%E5%A4%9A%E6%A8%A3%E6%80%A7',
      desc: t('map.markers.taiwanRapHipHop.desc'),
      county: 'nantou',
    },
    {
      id: 'taiwanElectronicMusic',
      type: 'nature',
      title: t('map.markers.taiwanElectronicMusic.title'),
      lat: 23.998947,
      lng: 121.601608,
      category: 'nature',
      region: 'east',
      link: '/nature/%E8%87%BA%E7%81%A3%E7%9A%84%E9%AF%A8%E8%B1%9A',
      desc: t('map.markers.taiwanElectronicMusic.desc'),
      county: 'hualien',
    },
    {
      id: 'taiwanTraditionalMusic',
      type: 'people',
      title: t('map.markers.taiwanTraditionalMusic.title'),
      lat: 25.032903,
      lng: 121.572712,
      category: 'people',
      region: 'north',
      link: '/people/%E4%BA%94%E6%9C%88%E5%A4%A9',
      desc: t('map.markers.taiwanTraditionalMusic.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanFilmIndustry',
      type: 'people',
      title: t('map.markers.taiwanFilmIndustry.title'),
      lat: 23.475759,
      lng: 120.445163,
      category: 'people',
      region: 'south',
      link: '/people/%E4%BC%8D%E4%BD%B0',
      desc: t('map.markers.taiwanFilmIndustry.desc'),
      county: 'chiayi',
    },
    {
      id: 'newTaiwanCinema',
      type: 'people',
      title: t('map.markers.newTaiwanCinema.title'),
      lat: 22.67864,
      lng: 120.477312,
      category: 'people',
      region: 'south',
      link: '/people/%E5%90%B3%E5%AF%B6%E6%98%A5',
      desc: t('map.markers.newTaiwanCinema.desc'),
      county: 'pingtung',
    },
    {
      id: 'taiwanDocumentary',
      type: 'people',
      title: t('map.markers.taiwanDocumentary.title'),
      lat: 24.996722,
      lng: 121.294056,
      category: 'people',
      region: 'north',
      link: '/people/%E5%91%82%E7%A7%80%E8%93%AE',
      desc: t('map.markers.taiwanDocumentary.desc'),
      county: 'taoyuan',
    },
    {
      id: 'taiwanAnimationIndustry',
      type: 'people',
      title: t('map.markers.taiwanAnimationIndustry.title'),
      lat: 24.752,
      lng: 121.753,
      category: 'people',
      region: 'north',
      link: '/people/%E5%B9%BE%E7%B1%B3',
      desc: t('map.markers.taiwanAnimationIndustry.desc'),
      county: 'yilan',
    },
    {
      id: 'taiwanTelevisionIndustry',
      type: 'people',
      title: t('map.markers.taiwanTelevisionIndustry.title'),
      lat: 22.633624,
      lng: 120.30421,
      category: 'people',
      region: 'south',
      link: '/people/%E6%88%B4%E8%B3%87%E7%A9%8E',
      desc: t('map.markers.taiwanTelevisionIndustry.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanOttPlatforms',
      type: 'people',
      title: t('map.markers.taiwanOttPlatforms.title'),
      lat: 24.048701,
      lng: 120.435493,
      category: 'people',
      region: 'central',
      link: '/people/%E6%9D%8E%E6%98%82',
      desc: t('map.markers.taiwanOttPlatforms.desc'),
      county: 'changhua',
    },
    {
      id: 'taiwanPodcastIndustry',
      type: 'people',
      title: t('map.markers.taiwanPodcastIndustry.title'),
      lat: 24.751698,
      lng: 121.747736,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9D%8E%E6%99%BA%E5%87%B1',
      desc: t('map.markers.taiwanPodcastIndustry.desc'),
      county: 'yilan',
    },
    {
      id: 'taiwanPublishing',
      type: 'people',
      title: t('map.markers.taiwanPublishing.title'),
      lat: 24.798569,
      lng: 120.963203,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9D%8E%E9%81%A0%E5%93%B2',
      desc: t('map.markers.taiwanPublishing.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanBookstoreCulture',
      type: 'people',
      title: t('map.markers.taiwanBookstoreCulture.title'),
      lat: 25.038453,
      lng: 121.571734,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9D%9C%E8%81%B0%E6%98%8E',
      desc: t('map.markers.taiwanBookstoreCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanComicMangaIndustry',
      type: 'people',
      title: t('map.markers.taiwanComicMangaIndustry.title'),
      lat: 25.02529,
      lng: 121.566985,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9E%97%E6%9B%B8%E8%B1%AA',
      desc: t('map.markers.taiwanComicMangaIndustry.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanGameIndustry',
      type: 'people',
      title: t('map.markers.taiwanGameIndustry.title'),
      lat: 25.029984,
      lng: 121.570337,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9E%97%E7%BE%A9%E5%82%91',
      desc: t('map.markers.taiwanGameIndustry.desc'),
      county: 'taipei',
    },
    {
      id: 'nationalPalaceMuseum',
      type: 'people',
      title: t('map.markers.nationalPalaceMuseum.title'),
      lat: 24.759419,
      lng: 121.757439,
      category: 'people',
      region: 'north',
      link: '/people/%E6%9E%97%E7%BE%A9%E9%9B%84',
      desc: t('map.markers.nationalPalaceMuseum.desc'),
      county: 'yilan',
    },
    {
      id: 'nationalParks',
      type: 'people',
      title: t('map.markers.nationalParks.title'),
      lat: 25.027642,
      lng: 121.571426,
      category: 'people',
      region: 'north',
      link: '/people/%E6%A5%8A%E5%BE%B7%E6%98%8C',
      desc: t('map.markers.nationalParks.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanGeography',
      type: 'people',
      title: t('map.markers.taiwanGeography.title'),
      lat: 25.029299,
      lng: 121.566647,
      category: 'people',
      region: 'north',
      link: '/people/%E7%99%BD%E5%85%88%E5%8B%87',
      desc: t('map.markers.taiwanGeography.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanClimate',
      type: 'people',
      title: t('map.markers.taiwanClimate.title'),
      lat: 22.991747,
      lng: 120.229115,
      category: 'people',
      region: 'south',
      link: '/people/%E7%9B%A7%E5%BB%A3%E4%BB%B2',
      desc: t('map.markers.taiwanClimate.desc'),
      county: 'tainan',
    },
    {
      id: 'taiwanEcosystem',
      type: 'people',
      title: t('map.markers.taiwanEcosystem.title'),
      lat: 22.62918,
      lng: 120.299673,
      category: 'people',
      region: 'south',
      link: '/people/%E8%8E%8A%E6%99%BA%E6%B7%B5',
      desc: t('map.markers.taiwanEcosystem.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanEndangeredSpecies',
      type: 'people',
      title: t('map.markers.taiwanEndangeredSpecies.title'),
      lat: 25.033768,
      lng: 121.568284,
      category: 'people',
      region: 'north',
      link: '/people/%E8%94%A1%E6%98%8E%E4%BA%AE',
      desc: t('map.markers.taiwanEndangeredSpecies.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanMarineEcology',
      type: 'people',
      title: t('map.markers.taiwanMarineEcology.title'),
      lat: 22.939152,
      lng: 120.218654,
      category: 'people',
      region: 'south',
      link: '/people/%E8%A8%B1%E6%96%87%E9%BE%8D',
      desc: t('map.markers.taiwanMarineEcology.desc'),
      county: 'tainan',
    },
    {
      id: 'taiwanBirdwatching',
      type: 'people',
      title: t('map.markers.taiwanBirdwatching.title'),
      lat: 24.754602,
      lng: 121.751035,
      category: 'people',
      region: 'north',
      link: '/people/%E8%A8%B1%E8%8A%B3%E5%AE%9C',
      desc: t('map.markers.taiwanBirdwatching.desc'),
      county: 'yilan',
    },
    {
      id: 'taiwanHotSprings',
      type: 'people',
      title: t('map.markers.taiwanHotSprings.title'),
      lat: 23.003849,
      lng: 120.232143,
      category: 'people',
      region: 'south',
      link: '/people/%E8%B3%B4%E6%B8%85%E5%BE%B7%EF%BC%9A%E5%BE%9E%E7%A4%A6%E5%B7%A5%E5%AE%B6%E5%BA%AD%E5%88%B0%E7%B8%BD%E7%B5%B1%E5%BA%9C%E7%9A%84%E5%85%AC%E5%85%B1%E8%A1%9B%E7%94%9F%E9%86%AB%E5%B8%AB',
      desc: t('map.markers.taiwanHotSprings.desc'),
      county: 'tainan',
    },
    {
      id: 'taiwanIslands',
      type: 'people',
      title: t('map.markers.taiwanIslands.title'),
      lat: 22.756,
      lng: 121.144,
      category: 'people',
      region: 'east',
      link: '/people/%E9%83%AD%E5%A9%9E%E6%B7%B3',
      desc: t('map.markers.taiwanIslands.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanMountains',
      type: 'people',
      title: t('map.markers.taiwanMountains.title'),
      lat: 24.999664,
      lng: 121.301453,
      category: 'people',
      region: 'north',
      link: '/people/%E9%84%A7%E9%9B%A8%E8%B3%A2',
      desc: t('map.markers.taiwanMountains.desc'),
      county: 'taoyuan',
    },
    {
      id: 'taiwanRivers',
      type: 'people',
      title: t('map.markers.taiwanRivers.title'),
      lat: 22.628425,
      lng: 120.307078,
      category: 'people',
      region: 'south',
      link: '/people/%E9%8D%BE%E7%90%86%E5%92%8C',
      desc: t('map.markers.taiwanRivers.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'taiwanCoastline',
      type: 'people',
      title: t('map.markers.taiwanCoastline.title'),
      lat: 22.762658,
      lng: 121.147155,
      category: 'people',
      region: 'east',
      link: '/people/%E9%99%B3%E6%A8%B9%E8%8F%8A',
      desc: t('map.markers.taiwanCoastline.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanForests',
      type: 'people',
      title: t('map.markers.taiwanForests.title'),
      lat: 25.027606,
      lng: 121.564221,
      category: 'people',
      region: 'north',
      link: '/people/%E9%99%B3%E6%B0%B4%E6%89%81',
      desc: t('map.markers.taiwanForests.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanNaturalDisasters',
      type: 'people',
      title: t('map.markers.taiwanNaturalDisasters.title'),
      lat: 25.032015,
      lng: 121.562872,
      category: 'people',
      region: 'north',
      link: '/people/%E9%A6%AC%E8%8B%B1%E4%B9%9D',
      desc: t('map.markers.taiwanNaturalDisasters.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanEarthquakes',
      type: 'people',
      title: t('map.markers.taiwanEarthquakes.title'),
      lat: 24.75202,
      lng: 121.755675,
      category: 'people',
      region: 'north',
      link: '/people/%E9%BB%83%E6%98%A5%E6%98%8E',
      desc: t('map.markers.taiwanEarthquakes.desc'),
      county: 'yilan',
    },
    {
      id: 'taiwanTyphoons',
      type: 'people',
      title: t('map.markers.taiwanTyphoons.title'),
      lat: 23.48414,
      lng: 120.453621,
      category: 'people',
      region: 'south',
      link: '/people/%E9%BB%83%E9%9C%87%E5%8D%97%EF%BC%9A%E8%97%8F%E6%9B%B8%E7%95%8C%E7%AB%B9%E9%87%8E%E5%85%A7%E8%B1%90%E8%88%87%E5%8F%B0%E7%81%A3%E6%96%87%E5%8F%B2%E7%9A%84%E6%B4%BB%E6%B0%B4%E6%BA%90%E9%A0%AD',
      desc: t('map.markers.taiwanTyphoons.desc'),
      county: 'chiayi',
    },
    {
      id: 'sunflowerMovement',
      type: 'society',
      title: t('map.markers.sunflowerMovement.title'),
      lat: 24.805423,
      lng: 120.971643,
      category: 'society',
      region: 'north',
      link: '/society/%E5%8B%95%E7%89%A9%E5%9C%92%E8%88%87%E5%B1%95%E6%BC%94%E5%8B%95%E7%89%A9%E5%80%AB%E7%90%86',
      desc: t('map.markers.sunflowerMovement.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanSocialMovements',
      type: 'society',
      title: t('map.markers.taiwanSocialMovements.title'),
      lat: 24.161639,
      lng: 121.621216,
      category: 'society',
      region: 'east',
      link: '/society/%E5%8F%B0%E7%81%A3%E5%8E%9F%E4%BD%8F%E6%B0%91%E6%97%8F%E5%9C%9F%E5%9C%B0%E6%AD%A3%E7%BE%A9%E8%88%87%E5%82%B3%E7%B5%B1%E9%A0%98%E5%9F%9F',
      desc: t('map.markers.taiwanSocialMovements.desc'),
      county: 'hualien',
    },
    {
      id: 'taiwanMarriageEquality',
      type: 'society',
      title: t('map.markers.taiwanMarriageEquality.title'),
      lat: 25.0408,
      lng: 121.56271,
      category: 'society',
      region: 'north',
      link: '/society/%E5%8F%B0%E7%81%A3%E5%90%8C%E5%A9%9A%E8%88%87%E6%80%A7%E5%88%A5%E5%B9%B3%E6%AC%8A',
      desc: t('map.markers.taiwanMarriageEquality.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanEnvironmentalJustice',
      type: 'society',
      title: t('map.markers.taiwanEnvironmentalJustice.title'),
      lat: 22.03693,
      lng: 121.550938,
      category: 'society',
      region: 'east',
      link: '/society/%E5%8F%B0%E7%81%A3%E7%92%B0%E5%A2%83%E6%AD%A3%E7%BE%A9%E8%88%87%E9%84%B0%E9%81%BF%E7%88%AD%E8%AD%B0',
      desc: t('map.markers.taiwanEnvironmentalJustice.desc'),
      county: 'taitung',
    },
    {
      id: 'taiwanCommunityRiCulture',
      type: 'society',
      title: t('map.markers.taiwanCommunityRiCulture.title'),
      lat: 25.032173,
      lng: 121.557437,
      category: 'society',
      region: 'north',
      link: '/society/%E5%8F%B0%E7%81%A3%E7%A4%BE%E5%8D%80%E8%88%87%E9%87%8C%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanCommunityRiCulture.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanLongTermCare',
      type: 'society',
      title: t('map.markers.taiwanLongTermCare.title'),
      lat: 25.03609,
      lng: 121.559587,
      category: 'society',
      region: 'north',
      link: '/society/%E5%8F%B0%E7%81%A3%E9%95%B7%E6%9C%9F%E7%85%A7%E9%A1%A7%E5%88%B6%E5%BA%A6%E7%99%BC%E5%B1%95',
      desc: t('map.markers.taiwanLongTermCare.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanLaborMovement',
      type: 'society',
      title: t('map.markers.taiwanLaborMovement.title'),
      lat: 24.051249,
      lng: 120.432856,
      category: 'society',
      region: 'central',
      link: '/society/%E7%92%B0%E4%BF%9D%E8%88%87%E6%B0%B8%E7%BA%8C%E7%99%BC%E5%B1%95',
      desc: t('map.markers.taiwanLaborMovement.desc'),
      county: 'changhua',
    },
    {
      id: 'taiwanHousingIssues',
      type: 'society',
      title: t('map.markers.taiwanHousingIssues.title'),
      lat: 25.02882,
      lng: 121.568618,
      category: 'society',
      region: 'north',
      link: '/society/%E7%A4%BE%E6%9C%83%E4%BD%8F%E5%AE%85%E8%88%87%E5%B1%85%E4%BD%8F%E6%AD%A3%E7%BE%A9',
      desc: t('map.markers.taiwanHousingIssues.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanHealthcareSystem',
      type: 'technology',
      title: t('map.markers.taiwanHealthcareSystem.title'),
      lat: 24.779271,
      lng: 121.000458,
      category: 'technology',
      region: 'north',
      link: '/technology/%E7%A7%91%E6%8A%80%E5%9C%92%E5%8D%80%E7%99%BC%E5%B1%95',
      desc: t('map.markers.taiwanHealthcareSystem.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanImmigration',
      type: 'technology',
      title: t('map.markers.taiwanImmigration.title'),
      lat: 24.79136,
      lng: 120.998278,
      category: 'technology',
      region: 'north',
      link: '/technology/%E5%8D%8A%E5%B0%8E%E9%AB%94%E7%94%A2%E6%A5%AD',
      desc: t('map.markers.taiwanImmigration.desc'),
      county: 'hsinchu',
    },
    {
      id: 'taiwanReligiousDiversity',
      type: 'geography',
      title: t('map.markers.taiwanReligiousDiversity.title'),
      lat: 25.199193,
      lng: 121.694114,
      category: 'geography',
      region: 'north',
      link: '/geography/%E5%8F%B0%E7%81%A3%E6%B5%B7%E5%B2%B8%E5%9C%B0%E5%BD%A2%E8%88%87%E6%B5%B7%E6%B4%8B%E5%9C%B0%E6%99%AF',
      desc: t('map.markers.taiwanReligiousDiversity.desc'),
      county: 'newTaipei',
    },
    {
      id: 'taiwanBuddhismTaoism',
      type: 'food',
      title: t('map.markers.taiwanBuddhismTaoism.title'),
      lat: 25.038892,
      lng: 121.567251,
      category: 'food',
      region: 'north',
      link: '/food/台灣茶文化',
      desc: t('map.markers.taiwanBuddhismTaoism.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanFolkReligion',
      type: 'society',
      title: t('map.markers.taiwanFolkReligion.title'),
      lat: 25.030572,
      lng: 121.572749,
      category: 'society',
      region: 'north',
      link: '/society/%E5%8F%B0%E7%81%A3%E9%81%B8%E8%88%89%E8%88%87%E6%94%BF%E9%BB%A8%E6%94%BF%E6%B2%BB',
      desc: t('map.markers.taiwanFolkReligion.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanChristianity',
      type: 'lifestyle',
      title: t('map.markers.taiwanChristianity.title'),
      lat: 25.032633,
      lng: 121.559385,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%8F%B0%E7%81%A3%E9%83%BD%E5%B8%82%E7%99%BC%E5%B1%95%E8%88%87%E5%9F%8E%E9%84%89%E5%B7%AE%E8%B7%9D',
      desc: t('map.markers.taiwanChristianity.desc'),
      county: 'taipei',
    },
    {
      id: 'taiwanIslamJudaism',
      type: 'lifestyle',
      title: t('map.markers.taiwanIslamJudaism.title'),
      lat: 25.039142,
      lng: 121.570184,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E5%9F%8E%E5%B8%82%E7%89%B9%E8%89%B2%E8%88%87%E5%8D%80%E5%9F%9F%E6%96%87%E5%8C%96',
      desc: t('map.markers.taiwanIslamJudaism.desc'),
      county: 'taipei',
    },
    {
      id: 'kaohsiungIncident',
      type: 'society',
      title: t('map.markers.kaohsiungIncident.title'),
      lat: 22.629481,
      lng: 120.302211,
      category: 'society',
      region: 'south',
      link: '/society/%E6%B0%91%E4%B8%BB%E5%8C%96',
      desc: t('map.markers.kaohsiungIncident.desc'),
      county: 'kaohsiung',
    },
    {
      id: 'wangLeeOlympicGold',
      type: 'lifestyle',
      title: t('map.markers.wangLeeOlympicGold.title'),
      lat: 25.040765,
      lng: 121.562491,
      category: 'lifestyle',
      region: 'north',
      link: '/lifestyle/%E7%8E%8B%E9%BD%8A%E9%BA%9F%E8%88%87%E6%9D%8E%E6%B4%8B%EF%BC%88%E9%BA%9F%E6%B4%8B%E9%85%8D%EF%BC%89',
      desc: t('map.markers.wangLeeOlympicGold.desc'),
      county: 'taipei',
    },
  ];
}

export {
  getMapRoutes,
  getMapMarkers,
  type MarkerCategory,
  type MarkerRegion,
  type County,
};
